site_name: Hedy Lamarr

repo_name: "Hedy Lamarr"
repo_url: "https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T01-HEDY-LAMAR"

site_description: Documentação do projeto do grupo Hedy Lamar de Qualidade de Software (2025.1), Turma 1

nav:
  - Início: index.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.sections
    - navigation.indexes
    - navigation.instant
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.pills
    - navigation.expand
    - navigation.tracking
    - content.code.annotate
    - content.code.highlight
    - content.code.linenumbers
    - content.footnotes
    - content.heading.permalinks
    - content.heading.anchor
    - content.heading.toc

  language: pt

  font:
    text: "Roboto"
    code: "sans-serif"

  palette:
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: "#03161A"

    - scheme: default
      toggle:
        icon: material/weather-sunny
      primary: "#03161A"
      accent: black

  logo: img/icon.jpg
  favicon: img/icon.jpg

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: false
      clickable_checkbox: true